heat_template_version: queens

parameters:

  index:
    type: number
    description: Index of the OS::Heat::ResourceGroup itteration

  server_name_prefix:
    type: string
    description: The prefix to use for the server name

  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the server

  flavor:
    type: string
    description: Instance type for the server

  image_id:
    type: string
    description: Name or ID of the image to use for the server

  management_net:
    type: string
    description: Name of the project's mangement network

  public_net:
    type: string
    description: Name or ID of the Ceph public network

  ssh_security_group:
    type: string
    description: Name or ID of the SSH security group

  ceph_mon_security_group:
    type: string
    description: Name or ID of the Ceph monitor security group

  ceph_rgws_security_group:
    type: string
    description: Name or ID of the Ceph object gateway security group


resources:

  ceph_mon_server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: prefix-mon-index
          params:
            prefix: { get_param: server_name_prefix }
            index: { get_param: index }
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - network: { get_param: management_net }
        - network: { get_param: public_net }
      security_groups:
        - { get_param: ssh_security_group }
        - { get_param: ceph_mon_security_group }
        - { get_param: ceph_rgws_security_group }
      user_data: |
        #!/bin/sh -x

        /bin/echo '#### Make eth0 the default gateway'

        /bin/echo 'GATEWAYDEV=eth0' >> /etc/sysconfig/network

        /bin/echo '#### Configure eth1'

        /bin/cat > /etc/sysconfig/network-scripts/ifcfg-eth1 << EOF1
        BOOTPROTO=dhcp
        DEVICE=eth1
        ONBOOT=yes
        TYPE=Ethernet
        USERCTL=no
        EOF1

        /bin/echo '#### Bring up eth1'

        /etc/sysconfig/network-scripts/ifup eth1


outputs:

  ceph_mon_server_name:
    description: Ceph mon server name
    value: { get_attr: [ceph_mon_server, name] }

  ceph_mon_management_address:
    description: Ceph mon management address
    value: { get_attr: [ceph_mon_server, first_address] }