heat_template_version: queens

parameters:

  index:
    type: number
    description: Index of the ceph_osd OS::Heat::ResourceGroup itteration

  server_name_prefix:
    type: string
    description: The prefix to use for the server name

  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the server

  flavor:
    type: string
    description: Instance type for the server

  image_id:
    type: string
    description: Name or ID of the image to use for the server

  management_net:
    type: string
    description: Name of the project's mangement network

  ceph_net:
    type: string
    description: Name or ID of the Ceph network

  floating_ip_net:
    type: string
    description: Name of the external network

  ssh_security_group:
    type: string
    description: Name or ID of the SSH security group

  ceph_osd_security_group:
    type: string
    description: Name or ID of the Ceph OSD security group

  num_osd_volumes:
    type: number
    description: Number of volumes to create for each Ceph OSD server

  osd_volume_size:
    type: number
    description: Size of the OSD volume in GB

  availability_zone:
    type: string
    description: The availability zone used to create the resources

  assign_floating_ips:
    type: boolean
    description: Assign floating ips to all servers
    default: false

conditions:

  evaluate_floating_ips:
    equals:
      - get_param: assign_floating_ips
      - true

resources:

  ceph_osd_server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: prefix-osd-index
          params:
            prefix: { get_param: server_name_prefix }
            index: { get_param: index }
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: ceph_osd_management_net_port }
        - port: { get_resource: ceph_osd_ceph_net_port }
      user_data: |
        #!/bin/sh -x

        /bin/echo '#### Make eth0 the default gateway'

        /bin/echo 'GATEWAYDEV=eth0' >> /etc/sysconfig/network

        /bin/echo '#### Configure eth1'

        /bin/cat > /etc/sysconfig/network-scripts/ifcfg-eth1 << EOF1
        BOOTPROTO=dhcp
        DEVICE=eth1
        ONBOOT=yes
        TYPE=Ethernet
        USERCTL=no
        EOF1

        /bin/echo '#### Bring up eth1'

        /etc/sysconfig/network-scripts/ifup eth1

  ceph_osd_management_net_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: management_net }
      security_groups:
        - { get_param: ssh_security_group }

  ceph_osd_ceph_net_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: ceph_net }
      security_groups:
        - { get_param: ceph_osd_security_group }

  ceph_osd_floating_ip:
    type: "OS::Neutron::FloatingIP"
    condition: evaluate_floating_ips
    properties:
      floating_network: { get_param: floating_ip_net }
      port_id: { get_resource: ceph_osd_management_net_port }

  ceph_osd_volume:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: num_osd_volumes }
      resource_def:
        type: ceph_osd_volume.yaml
        properties:
          size: { get_param: osd_volume_size }
          availability_zone: { get_param: availability_zone }
          instance_uuid: { get_resource: ceph_osd_server }

outputs:

  ceph_osd_server_name:
    description: Ceph osd server name
    value: { get_attr: [ceph_osd_server, name] }

  ceph_osd_management_address:
    description: Ceph osd management address
    value: { if: [evaluate_floating_ips, { get_attr: [ ceph_osd_floating_ip, floating_ip_address ] }, { get_attr: [ceph_osd_server, first_address] }] }