heat_template_version: queens

parameters:

  index:
    type: number
    description: Index of the OS::Heat::ResourceGroup itteration

  server_name_prefix:
    type: string
    description: The prefix to use for the server name

  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the server

  flavor:
    type: string
    description: Instance type for the server

  image_id:
    type: string
    description: Name or ID of the image to use for the server

  management_net:
    type: string
    description: Name of the project's mangement network

  ssh_security_group:
    type: string
    description: Name or ID of the SSH security group

  k8s_security_group:
    type: string
    description: Name or ID of the k8s security group

resources:

  k8s_master_server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: prefix-master-index
          params:
            prefix: { get_param: server_name_prefix }
            index: { get_param: index }
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - network: { get_param: management_net }
      security_groups:
        - { get_param: ssh_security_group }
        - { get_param: k8s_security_group }

outputs:

  k8s_master_server_name:
    description: Kubernetes master server name
    value: { get_attr: [k8s_master_server, name] }

  k8s_master_management_address:
    description: Kubernetes master management address
    value: { get_attr: [k8s_master_server, first_address] }