heat_template_version: queens

parameters:

  index:
    type: number
    description: Index of the ceph_osd OS::Heat::ResourceGroup itteration

  server_name_prefix:
    type: string
    description: The prefix to use for the server name

  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the server

  flavor:
    type: string
    description: Instance type for the server

  image_id:
    type: string
    description: Name or ID of the image to use for the server

  management_net:
    type: string
    description: Name of the project's mangement network

  ssh_security_group:
    type: string
    description: Name or ID of the SSH security group

  k8s_security_group:
    type: string
    description: Name or ID of the Kubernetes security group

  num_node_volumes:
    type: number
    description: Number of volumes to create for each Kubernetes worker node server

  node_volume_size:
    type: number
    description: Size of the Kubernetes worker node volume in GB

  availability_zone:
    type: string
    description: The availability zone used to create the resources


resources:

  k8s_node_server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: prefix-node-index
          params:
            prefix: { get_param: server_name_prefix }
            index: { get_param: index }
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - network: { get_param: management_net }
      security_groups:
        - { get_param: ssh_security_group }
        - { get_param: k8s_security_group }

  k8s_node_volume:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: num_node_volumes }
      resource_def:
        type: k8s_node_volume.yaml
        properties:
          size: { get_param: node_volume_size }
          availability_zone: { get_param: availability_zone }
          instance_uuid: { get_resource: k8s_node_server }

outputs:

  k8s_node_server_name:
    description: Kubernetes worker node server name
    value: { get_attr: [k8s_node_server, name] }

  k8s_node_management_address:
    description: Kubernetes worker node management address
    value: { get_attr: [k8s_node_server, first_address] }