---
heat_template_version: queens

parameters:

  index:
    type: number
    description: Index of the OS::Heat::ResourceGroup itteration

  server_name_prefix:
    type: string
    description: The prefix to use for the server name

  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the server

  flavor:
    type: string
    description: Instance type for the server

  image_id:
    type: string
    description: Name or ID of the image to use for the server

  management_net:
    type: string
    description: Name of the project's mangement network

  ssh_security_group:
    type: string
    description: Name or ID of the SSH security group

  k8s_security_group:
    type: string
    description: Name or ID of the k8s security group

resources:

  k8s_control_plane_server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: prefix-cp-index
          params:
            prefix: { get_param: server_name_prefix }
            index: { get_param: index }
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: k8s_control_plane_management_net_port }

  k8s_control_plane_management_net_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: management_net }
      allowed_address_pairs:
        - ip_address: 10.233.0.0/18
        - ip_address: 10.233.64.0/18
      security_groups:
        - { get_param: ssh_security_group }
        - { get_param: k8s_security_group }

outputs:

  k8s_control_plane_server_name:
    description: Kubernetes control-plane server name
    value: { get_attr: [k8s_control_plane_server, name] }

  k8s_control_plane_management_address:
    description: Kubernetes control-plane management address
    value: { get_attr: [k8s_control_plane_server, first_address] }
